### ISSUE TITLE
Auditlog gets stuck in an infinite loop

### ISSUE THREAD

**Issue by fsfod** [raptorjit/raptorjit#180]
The Auditlog get can get stuck in an infinite loop inside ctype_repr from trying to log ctypes

```
#0  ctype_repr (id=104, ctr=0x7ffffffedf70) at lj_ctype.c:449
#1  lj_ctype_repr (L=0x7fffff7b0378, id=104, name=<optimized out>) at lj_ctype.c:550
#2  0x000000000801b762 in lj_ctype_log (L=0x7fffff7b0378) at lj_ctype.c:634
#3  0x0000000008018ec3 in trace_save (T=0x7fffff518518, J=0x7fffff7b0680) at lj_trace.c:128
#4  trace_stop (J=0x7fffff7b0680) at lj_trace.c:469
#5  trace_state (L=<optimized out>, dummy=<optimized out>, ud=0x7fffff7b0680) at lj_trace.c:610
#6  0x0000000008022f33 in lj_vm_cpcall ()
#7  0x000000000801939e in lj_trace_ins (J=0x7fffff7b0680, pc=pc@entry=0x7fffff7b0530) at lj_trace.c:641
#8  0x000000000800a99c in lj_dispatch_call (L=0x7fffff7b0378, pc=0x7fffff7b0534) at lj_dispatch.c:424
#9  0x000000000802494d in lj_vm_hotcall ()
#10 0x0000000008010098 in lua_pcall (L=<optimized out>, nargs=<optimized out>, nresults=<optimized out>, errfunc=<optimized out>) at lj_api.c:1074
#11 0x0000000008005ade in docall (L=0x7fffff7b0378, narg=3, clear=0) at luajit.c:108
#12 0x00000000080069de in handle_script (argx=<optimized out>, L=0x7fffff7b0378) at luajit.c:276
#13 pmain (L=0x7fffff7b0378) at luajit.c:554
#14 0x0000000008022b25 in lj_BC_FUNCC ()
#15 0x00000000080100ed in lua_cpcall (L=<optimized out>, func=<optimized out>, ud=<optimized out>) at lj_api.c:1098
#16 0x00000000080055e6 in main (argc=5, argv=0x7ffffffee598) at luajit.c:583
``

**Comment by lukego** [comment]
Ouch. Do you have any idea how that is happening? How are you triggering this?

I had hoped this was resolved via #165 but I confess that I haven't really made sense of the ctype formatting code yet myself.

**Comment by lukego** [comment]
It's only a band-aid but does #184 help?

**Comment by fsfod** [comment]
It seems to.
